services:
  website:
    build: ./website
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - SECRET
      - HOSTS
      - DB_PASSWORD
      - DB_USER=subterfuge
      - DB_HOST=db
      - DB_NAME=subterfuge
    volumes:
      - ./data:/data/import
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=subterfuge
      - POSTGRES_DB=subterfuge
    volumes:
      - ./db:/var/lib/postgresql
