# Generated by Django 3.2.25 on 2024-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['-timestamp'], name='leaderboard_timesta_ab19b4_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['player', 'leaderboard'], name='leaderboard_player__96219a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['leaderboard', '-rank'], name='leaderboard_leaderb_02a583_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='leaderboard_name_a20ada_idx'),
        ),
    ]
