# Generated by Django 3.2.7 on 2021-09-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('rank', models.IntegerField()),
                ('elo', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('bronze', models.IntegerField()),
                ('ratedgames', models.IntegerField()),
                ('totalgames', models.IntegerField()),
                ('finished', models.IntegerField()),
                ('eliminated', models.IntegerField()),
                ('resigned', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('player', 'timestamp'), name='single player at time'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('rank', 'timestamp'), name='single rank at time'),
        ),
    ]
