# Generated by Django 3.2.7 on 2021-09-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20210927_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='source_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaderboard.sourcefile'),
        ),
    ]
